// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6315LoDmILFnmXGLqEovXuMd_J2I2-tc',
    appId: '1:113955999228:web:088004d10886871e1bb679',
    messagingSenderId: '113955999228',
    projectId: 'todoappriverpod',
    authDomain: 'todoappriverpod.firebaseapp.com',
    storageBucket: 'todoappriverpod.appspot.com',
    measurementId: 'G-KQJMSNMG9F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBPqZJwnW7XuH86hUhhdg9GGOYe5V2nKc',
    appId: '1:113955999228:android:d1f595f9c515291d1bb679',
    messagingSenderId: '113955999228',
    projectId: 'todoappriverpod',
    storageBucket: 'todoappriverpod.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRf91k9qA5VB_0jxEPdMiucWf0e86mpGg',
    appId: '1:113955999228:ios:3b52c8804ddec6bf1bb679',
    messagingSenderId: '113955999228',
    projectId: 'todoappriverpod',
    storageBucket: 'todoappriverpod.appspot.com',
    iosClientId: '113955999228-dv0gmm1f4hakqhaitncq2klou3q11d3m.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterRiverpodToDoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCRf91k9qA5VB_0jxEPdMiucWf0e86mpGg',
    appId: '1:113955999228:ios:3b52c8804ddec6bf1bb679',
    messagingSenderId: '113955999228',
    projectId: 'todoappriverpod',
    storageBucket: 'todoappriverpod.appspot.com',
    iosClientId: '113955999228-dv0gmm1f4hakqhaitncq2klou3q11d3m.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterRiverpodToDoApp',
  );
}
